[package]
name = "c01-invoking-llm"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { workspace = true }
reqwest = { workspace = true }
serde_json = { workspace = true }
serde = { version = "1.0.228", features = ["derive"] }
